### PR TITLE
Use TargetExt instead of OutputType

### LINKED ISSUE #4: Issue with winforms project
Hi,

It does not work out of the box with my VB Winforms project (under VS2017). Here's the MSBuild log message. The output type is 'WinExe' instead of the expected 'Exe'.

Cible "SetLargeAddressAware" ignorée en raison d'une fausse condition ; ( '$(LargeAddressAware)' == 'true' And Exists('$(LargeAddressAwareAssemblyFile)') And '$(OutputType)' == 'Exe' And '$(PlatformTarget)' == 'x86' ) a été évaluée comme ( 'true' == 'true' And Exists('C:\Users\Samuel\Documents\Code\syncrun.net\Clients\RTA_Shawinigan\packages\LargeAddressAware.1.0.2\build\net46\SetLargeAddressAware.dll') And 'WinExe' == 'Exe' And 'x86' == 'x86' ).

When I change 'Exe' to 'WinExe' in the targets file it does work.

This documentation could be useful: https://msdn.microsoft.com/en-us/library/bb629394.aspx (See OutputType section for all possible OutputType values)

### PR DESCRIPTION
**Pull request by jeffkl**
Should fix #4

### CODE REVIEW

**Comment by jeffkl** [comment]
@rainersigwald does this seem like a good fix as well?

**Comment by rainersigwald** [comment]
Doesn't look right to me--why should this work only for projects with the extension `dll`?

**Comment by jeffkl** [comment]
It goes in the PE headers which is only read by the operating system when executing an application right?  Do DLLs have this functionality?  An EXE is not large address aware but a DLL is, does the OS make the execution within in the DLL large address aware?

**Comment by KirillOsenkov** [comment]
Yeah, that's not right, it's specifically for .exes and not .dlls. The OS determines the address space when starting the application. It doesn't care about that bit for .dlls.

I've made another fix here:
https://github.com/KirillOsenkov/LargeAddressAware/commit/909a19781b5c70d1ab9f9e0cb467a28e60579504

**Pull request closed without merging**
